/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DocumentMeta = IDL.Record({
  'id' : IDL.Text,
  'lastEdited' : IDL.Int,
  'formatType' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'lastEdited' : IDL.Int,
  'formatType' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
});

export const idlService = IDL.Service({
  'createDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'getAllDocumentsMeta' : IDL.Func([], [IDL.Vec(DocumentMeta)], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
  'getDocumentMeta' : IDL.Func([IDL.Text], [DocumentMeta], ['query']),
  'updateDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DocumentMeta = IDL.Record({
    'id' : IDL.Text,
    'lastEdited' : IDL.Int,
    'formatType' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'lastEdited' : IDL.Int,
    'formatType' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
  });
  
  return IDL.Service({
    'createDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'getAllDocumentsMeta' : IDL.Func([], [IDL.Vec(DocumentMeta)], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
    'getDocumentMeta' : IDL.Func([IDL.Text], [DocumentMeta], ['query']),
    'updateDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };